### ISSUE TITLE
Quota not working with edgemicro

### ISSUE THREAD

**Issue by ssudhindra** [apigee-internal/microgateway#145] opened 2017-10-01 16:28 UTC
Configured a simple passthrough proxy on demo24 and demo34 orgs with edgemicro init and configure steps. I see below issues with versions 2.4.6 and the latest 2.5.4
1. When a quota policy is introduced in configure YML, edgemicro start fails with error:

```
/usr/local/lib/node_modules/edgemicro/node_modules/volos-quota-common/lib/quota.js:158
  throw new Error(util.format('%s must be a number', name));
  ^

Error: interval must be a number
    at checkNumber (/usr/local/lib/node_modules/edgemicro/node_modules/volos-quota-common/lib/quota.js:158:9)
    at new Quota (/usr/local/lib/node_modules/edgemicro/node_modules/volos-quota-common/lib/quota.js:52:22)
    at Object.create (/usr/local/lib/node_modules/edgemicro/node_modules/volos-quota-apigee/lib/apigeequota.js:56:10)
    at /usr/local/lib/node_modules/edgemicro/node_modules/microgateway-plugins/quota/index.js:25:23
    at Array.forEach (native)
    at Object.module.exports.init (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-plugins/quota/index.js:17:23)
    at wrapper (/usr/local/lib/node_modules/edgemicro/node_modules/lodash/index.js:3095:19)
    at Plugins.loadPlugin (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-core/lib/plugins.js:58:18)
    at Gateway.addPlugin (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-core/index.js:57:37)
    at /usr/local/lib/node_modules/edgemicro/lib/plugins.js:58:13
```

2. On filling up all the products in org with quota numbers, I get past the above error but land up in below issue and quota is not enforced.

```
edgemicro start -o demo34 -e test -k <key> -s <secret>
current nodejs version is v6.11.0
current edgemicro version is 2.4.6
info: jwt_public_key download from https://demo34-test.apigee.net/edgemicro-auth/publicKey returned 200 OK
info: products download from https://demo34-test.apigee.net/edgemicro-auth/products returned 200 OK
info: config download from https://edgemicroservices-us-east-1.apigee.net/edgemicro/bootstrap/organization/demo34/environment/test returned 200 OK
PROCESS PID : 40705
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
Not enough info for configuring quota
```

Config YML:
```yaml
edge_config:
  bootstrap: >-
    https://edgemicroservices-us-east-1.apigee.net/edgemicro/bootstrap/organization/demo34/environment/test
  jwt_public_key: 'https://demo34-test.apigee.net/edgemicro-auth/publicKey'
  managementUri: 'https://api.enterprise.apigee.com'
  vaultName: microgateway
  authUri: 'https://%s-%s.apigee.net/edgemicro-auth'
  baseUri: >-
    https://edgemicroservices.apigee.net/edgemicro/%s/organization/%s/environment/%s
  bootstrapMessage: Please copy the following property to the edge micro agent config
  keySecretMessage: The following credentials are required to start edge micro
  products: 'https://demo34-test.apigee.net/edgemicro-auth/products'
edgemicro:
  port: 8000
  max_connections: 1000
  max_connections_hard: 5000
  max_times: 300
  config_change_poll_interval: 600
  logging:
    level: error
    dir: /var/tmp
    stats_log_interval: 60
    rotate_interval: 24
  plugins:
    sequence:
      - oauth
      - quota
headers:
  x-forwarded-for: true
  x-forwarded-host: true
  x-request-id: true
  x-response-time: true
  via: true
oauth:
  allowNoAuthorization: false
  allowInvalidAuthorization: false
  verify_api_key_url: 'https://demo34-test.apigee.net/edgemicro-auth/verifyApiKey'
analytics:
  uri: >-
    https://edgemicroservices-us-east-1.apigee.net/edgemicro/axpublisher/organization/demo34/environment/test
```

[demo34-test-cache-config.yaml.txt](https://github.com/apigee-internal/microgateway/files/1347398/demo34-test-cache-config.yaml.txt)

**Comment by srinandan** [comment] 2017-10-01 18:36
this has been fixed in the code. the next release will have the fix.

**Comment by ssudhindra** [comment] 2017-10-01 18:54
Can you point me to a version where this is currently not an issue? Like 2.3.x?

**Comment by srinandan** [comment] 2017-10-02 20:07
the problem is not with just MG version, it is a combination of two things. If you upgrade the edgemicro-auth proxy, then it won't work with 2.3.X and higher. 

You'll have to upgrade the microgateway-plugins version to 2.3.15 (which has the fix). With this version of microgateway-plugins, it will work on 2.3.X or higher.

**Comment by srinandan** [comment] 2017-10-04 18:50
Please try with v2.5.7. This should be fixed in that version.

**Closed by srinandan** 2017-10-04 18:50 UTC
