### ISSUE TITLE
Proxy settings doesn't work as expected.

### ISSUE THREAD

**Issue by saucery** [apigee-internal/microgateway#57] opened 2016-10-11 15:55 UTC
As per documentation ( http://docs.apigee.com/microgateway/latest/edge-microgateway-operations ) it is possible to configure edge-microgateway to use proxy server for all outbound connections ( edge-microgateway -> backend server ):

"proxy: (default: none) Specifies the URL of a proxy server. If specified, all requests from Edge Microgateway will be sent via a connection to this proxy server. For more information, see Proxies in the Node.js request package documentation."

Unfortunately this works only partially - looks like only requests to *.apigee.net are being sent through configured proxy server.
Tested version : edge-microgateway version - 2.1.2.

I`ve also tried setting http_proxy / https_proxy on OS level ( export http_proxy="<proxy_ip>" and export https_proxy="<proxy_ip> ) and adding http-proxy , https-proxy and proxy to npm config file. Unfortunately this doesn't help.

**Comment by kevinswiber** [comment] 2016-10-12 17:05
Confirmed this is an issue.  I think we need to separate proxy config for `*.apigee.net` and for specific targets.

**Comment by asnowfix** [comment] 2017-01-31 22:28
Bug confirmed with 2.3.1. Using request(npm) with the same environment variables (http_proxy & hppts_proxy) does not exhibit the problem, so the issue is in EMG's code (an especially its HTTP client code).

**Comment by mdobson** [comment] 2017-01-31 22:39
I'll take a look at this.

**Comment by srinandan** [comment] 2017-05-23 17:17
This is now fixed. Can be closed.

**Closed** 2017-05-30 12:37 UTC

**Comment by dteirney** [comment] 2017-08-30 05:27
@srinandan is there a link to any issues/commits where this was resolved? We've just tried using the HTTPS_PROXY, HTTP_PROXY and NO_PROXY environment variables (there are no proxy_* variables in the configuration YAML file) and the target API requests are not respecting those environment variables. The requests made by EM directly to Edge Cloud are respecting them though.

**Comment by srinandan** [comment] 2017-09-16 01:47
can you please try with this method:
`edge_config:

    proxy: http://10.224.16.85:3128
    proxy_tunnel: true`

**Comment by WWitman** [comment] 2017-09-16 01:59
I can't start edgemicro when those configs are in the config file. If
that's what you mean, it just hangs.

-w


Will Witman |  Documentation, Apigee | Google Cloud|
 willwitman@google.com |  303-579-5977


On Fri, Sep 15, 2017 at 7:47 PM, Srinandan Sridhar <notifications@github.com

**Comment by WWitman** [comment] 2017-09-16 02:01
After timeout (a minute or so), this stack trace was output:

 edgemicro start -o docs -e test -k
19e9636c88f4c1ebdcf86df11fbca8b82aabb122a497601800ee20f86da27d52 -s
e54bad293355afe0716e167d0182f905c0f0c71ba4f3fcb25ae4f600cf58f86e
current nodejs version is v6.9.1
current edgemicro version is 2.5.4
warning: config download from
https://edgemicroservices-us-east-1.apigee.net/edgemicro/bootstrap/organization/docs/environment/test
returned  { Error: tunneling socket could not be established, cause=connect
ETIMEDOUT 10.224.16.85:3128
    at ClientRequest.onError
(/Users/willwitman/npm/lib/node_modules/edgemicro/node_modules/tunnel-agent/index.js:177:17)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code:
'ECONNRESET' }
warning: error downloading config, please check bootstrap configuration {
Error: tunneling socket could not be established, cause=connect ETIMEDOUT
10.224.16.85:3128
    at ClientRequest.onError
(/Users/willwitman/npm/lib/node_modules/edgemicro/node_modules/tunnel-agent/index.js:177:17)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code:
'ECONNRESET' }
failed to retieve config from gateway. continuing, will try cached copy..
{ Error: tunneling socket could not be established, cause=connect ETIMEDOUT
10.224.16.85:3128
    at ClientRequest.onError
(/Users/willwitman/npm/lib/node_modules/edgemicro/node_modules/tunnel-agent/index.js:177:17)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code:
'ECONNRESET' }
using cached configuration from
/Users/willwitman/.edgemicro/docs-test-cache-config.yaml
PROCESS PID : 4351
info: jwk_public_keys download from
https://docs-test.apigee.net/edgemicro-auth/jwkPublicKeys returned 200
undefined
warning: jwt_public_key download from
https://docs-test.apigee.net/edgemicro-auth/publicKey returned  { Error:
tunneling socket could not be established, cause=connect ETIMEDOUT
10.224.16.85:3128
    at ClientRequest.onError
(/Users/willwitman/npm/lib/node_modules/edgemicro/node_modules/tunnel-agent/index.js:177:17)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code:
'ECONNRESET' }
warning: products download from
https://docs-test.apigee.net/edgemicro-auth/products returned  { Error:
tunneling socket could not be established, cause=connect ETIMEDOUT
10.224.16.85:3128
    at ClientRequest.onError
(/Users/willwitman/npm/lib/node_modules/edgemicro/node_modules/tunnel-agent/index.js:177:17)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code:
'ECONNRESET' }




Will Witman |  Documentation, Apigee | Google Cloud|
 willwitman@google.com |  303-579-5977


On Fri, Sep 15, 2017 at 7:47 PM, Srinandan Sridhar <notifications@github.com

**Comment by dteirney** [comment] 2017-09-16 10:51
@srinandan we would like to be able to have the HTTP forwarding proxy configuration to be managed outside of the EM configuration file using the standard HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables. This allows us to more easily automatically deploy the EM runtime for an Org+Env without its configuration needing to have any direct knowledge of the networking environment it's running within.

Any idea why there appears to be a difference in behaviour between the API target HTTP requests and the requests made to Edge Cloud? Only the Edge Cloud requests appear to respect the HTTPS_PROXY environment variable configuration. In one case, the API target was https://httpbin.org but that wasn't sent through the data centre forwarding proxy unless we set that proxy within the EM configuration file.

We have both HTTP and HTTPS targets for some of our deploys (HTTP is only for the loopback address since the API target runs on the same node). Some of the HTTPS requests are local to the data centre so don't go through the forwarding proxy. Some need to go external so need to use the forwarding proxy, e.g. to httpbin for testing.

**Comment by srinandan** [comment] 2017-09-16 14:50
@dteirney - to confirm, the proxy setting (for target APIs) do work when set on the config file?
@WWitman - can you paste your config file please?

**Comment by WWitman** [comment] 2017-09-16 15:07
edge_config:
  bootstrap: >-
    https://edgemicroservices-us-east-1.apigee.net/edgemicro/bootstrap/organization/docs/environment/test
  jwt_public_key: 'https://docs-test.apigee.net/edgemicro-auth/publicKey'
  managementUri: 'https://api.enterprise.apigee.com'
  jwk_public_keys: 'https://docs-test.apigee.net/edgemicro-auth/jwkPublicKeys'
  vaultName: microgateway
  authUri: 'https://%s-%s.apigee.net/edgemicro-auth'
  baseUri: >-
    https://edgemicroservices.apigee.net/edgemicro/%s/organization/%s/environment/%s
  bootstrapMessage: Please copy the following property to the edge micro agent config
  keySecretMessage: The following credentials are required to start edge micro
  products: 'https://docs-test.apigee.net/edgemicro-auth/products'
  proxyPattern: edgemicro_*
  proxy: http://10.224.16.85:3128
  proxy_tunnel: true
edgemicro:
  port: 8000
  max_connections: 1000
  config_change_poll_interval: 600
  logging:
    level: error
    dir: /var/tmp
    stats_log_interval: 60
    rotate_interval: 24
  plugins:
    sequence:
      - oauth
headers:
  x-forwarded-for: true
  x-forwarded-host: true
  x-request-id: true
  x-response-time: true
  via: true
oauth:
  allowNoAuthorization: false
  allowInvalidAuthorization: false
  verify_api_key_url: 'https://docs-test.apigee.net/edgemicro-auth/verifyApiKey'
analytics:
  uri: >-
    https://edgemicroservices-us-east-1.apigee.net/edgemicro/axpublisher/organization/docs/environment/test

**Comment by srinandan** [comment] 2017-09-17 00:48
@WWitman - is that where your proxy server is running? You might want to try with a haproxy or nginx server. I see from the error, MG is unable to reach the proxy server (tunneling socket could not be established).

**Comment by anshul07** [comment] 2017-09-20 21:39
@srinandan  Edgemicro honours the standard PROXY environment variables (HTTP_PROXY, HTTPS_PROXY and NO_PROXY) only when proxy settings are configured in the configuration file, otherwise it completely ignores them.
